---
name: build-latest

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      -
        name: Install Python packages
        run: pip install -r requirements.txt pyinstaller pyinstaller-versionfile 

      - 
        name: Set commit version
        run: |
          echo "commit_ver=1.$(git rev-list HEAD --count)" >> $GITHUB_ENV
          echo "commit_hash=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      -
        name: Build executable
        run: pyinstaller --noconfirm --clean --onefile --console --name discord-rpc-client client.py
      -
        name: Make release zips
        run: |
          Compress-Archive -Path "dist\discord-rpc-client.exe" -CompressionLevel Optimal -DestinationPath .\discord-rpc-client-exe-${{ github.ref_name }}.zip
      -
        name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: discord-rpc_${{ env.commit_ver }}-${{ env.commit_hash }}
          path: dist